### ISSUE TITLE
safari css3动画闪烁bug

### ISSUE THREAD

**Issue by xwartz** [xwartz/xwartz.github.com#10]
http://stackoverflow.com/questions/2946748/iphone-webkit-css-animations-cause-flicker

参考这里，通过试验发现这个可以解决

``` css
body {-webkit-transform:translate3d(0,0,0);}
```

只有Safari闪烁，chrome和Firefox都正常..
